-- ============================================================
-- AEOrank — Supabase Schema
-- Run this in your Supabase SQL editor (Settings → SQL Editor)
-- ============================================================

-- ── USERS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id                 UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email              TEXT NOT NULL,
  stripe_customer_id TEXT UNIQUE,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own record"
  ON public.users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own record"
  ON public.users FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Service role can do anything on users"
  ON public.users FOR ALL
  USING (auth.role() = 'service_role');

-- ── SUBSCRIPTIONS ────────────────────────────────────────────
-- One row per Stripe subscription. Created at checkout.session.completed,
-- then kept in sync in place by customer.subscription.updated/.deleted and
-- invoice.payment_failed. `plan` matches the keys in lib/stripe.js PLANS.
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_customer_id     TEXT NOT NULL,
  stripe_subscription_id TEXT NOT NULL UNIQUE,
  plan                   TEXT NOT NULL CHECK (plan IN ('starter', 'growth', 'scale')),
  status                 TEXT NOT NULL, -- trialing/active/past_due/canceled/unpaid/incomplete/incomplete_expired
  brand                  TEXT,
  current_period_end     TIMESTAMPTZ,
  cancel_at_period_end   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions(user_id);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own subscriptions"
  ON public.subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on subscriptions"
  ON public.subscriptions FOR ALL
  USING (auth.role() = 'service_role');

-- ── REPORTS ──────────────────────────────────────────────────
-- One row per report generated by a LOGGED-IN visitor. This table alone is
-- the "score over time" data source (SELECT brand, score, created_at ORDER
-- BY created_at) — no separate snapshots table: every report generation IS
-- a snapshot, so a second table would just duplicate this one 1:1.
CREATE TABLE IF NOT EXISTS public.reports (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  brand       TEXT NOT NULL,
  url         TEXT,
  score       INTEGER,
  total       INTEGER NOT NULL DEFAULT 0,
  hits        INTEGER NOT NULL DEFAULT 0,
  competitors TEXT[] NOT NULL DEFAULT '{}',
  rows        JSONB, -- aiVisibility.rows: [{ query, model, live, answer, mentioned }]
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reports_user_id_created_at_idx ON public.reports(user_id, created_at DESC);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own reports"
  ON public.reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on reports"
  ON public.reports FOR ALL
  USING (auth.role() = 'service_role');

-- ── REPORT DRAFTS ────────────────────────────────────────────
-- Persisted version of the AI-drafted Reddit post suggestion + posted
-- status. Anonymous visitors never write here — PostDraftActions.js keeps
-- its current local-state-only behavior when there's no draftId. Nothing
-- in this table is ever posted to Reddit automatically; `posted` just
-- records that the customer says they posted it themselves.
CREATE TABLE IF NOT EXISTS public.report_drafts (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  report_id  UUID REFERENCES public.reports(id) ON DELETE CASCADE,
  subreddit  TEXT NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  posted     BOOLEAN NOT NULL DEFAULT FALSE,
  posted_at  TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS report_drafts_user_id_idx ON public.report_drafts(user_id);

ALTER TABLE public.report_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own drafts"
  ON public.report_drafts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own drafts"
  ON public.report_drafts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own drafts"
  ON public.report_drafts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on report_drafts"
  ON public.report_drafts FOR ALL
  USING (auth.role() = 'service_role');

-- ── AUTO-CREATE USER PROFILE ON SIGNUP ───────────────────────
-- Fires for every auth.users insert, whether from a real magic-link login
-- OR from admin.auth.admin.createUser() called by the Stripe webhook to
-- silently provision an account for someone who paid before ever logging in.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
