-- ============================================================
-- AEOrank — Supabase Schema
-- Run this in your Supabase SQL editor (Settings → SQL Editor)
-- ============================================================

-- ── USERS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id                 UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email              TEXT NOT NULL,
  stripe_customer_id TEXT UNIQUE,
  -- 'customer' (default) | 'poster' — posters are admin-invited accounts
  -- that fulfill tasks claimed from the shared pool, not customers
  -- themselves. See report_drafts.claimed_by below.
  role               TEXT NOT NULL DEFAULT 'customer',
  -- Set at role-flip time — either by lib/posterAccount.js (legacy
  -- admin-approval path) or app/api/poster/verify-reddit (current
  -- self-serve signup path) — the Reddit account they told us they'd
  -- post from. NULL for customers and for posters invited directly
  -- (app/api/admin/posters) without going through either apply flow.
  reddit_username    TEXT,
  -- Result of lib/reddit.js's checkRedditAccount() at the moment the role
  -- flipped to 'poster': 'active' (confirmed via Reddit OAuth, a direct
  -- fetch, or the Apify user-scraper actor — all read the account's real
  -- profile) | 'active_approx' (confirmed via Pullpush's historical
  -- archive instead — an approximation derived from post history, not
  -- the account itself) | 'unverified' (couldn't check any way — neither
  -- a rejection nor a confirmation). Never
  -- 'suspended'/'unavailable'/'too_new'/'low_karma'/'not_found'/'invalid'
  -- — those are rejected before the role ever flips.
  reddit_check_status TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own record"
  ON public.users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own record"
  ON public.users FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Service role can do anything on users"
  ON public.users FOR ALL
  USING (auth.role() = 'service_role');

-- ── SUBSCRIPTIONS ────────────────────────────────────────────
-- One row per Stripe subscription. Created at checkout.session.completed,
-- then kept in sync in place by customer.subscription.updated/.deleted and
-- invoice.payment_failed. `plan` matches the keys in lib/stripe.js PLANS.
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stripe_customer_id     TEXT NOT NULL,
  stripe_subscription_id TEXT NOT NULL UNIQUE,
  -- 'comp' = granted via a redeem code (see redeem_codes below), no real
  -- Stripe subscription behind it.
  plan                   TEXT NOT NULL CHECK (plan IN ('starter', 'growth', 'scale', 'comp')),
  status                 TEXT NOT NULL, -- trialing/active/past_due/canceled/unpaid/incomplete/incomplete_expired
  brand                  TEXT,
  current_period_end     TIMESTAMPTZ,
  cancel_at_period_end   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions(user_id);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own subscriptions"
  ON public.subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on subscriptions"
  ON public.subscriptions FOR ALL
  USING (auth.role() = 'service_role');

-- ── REDEEM CODES ─────────────────────────────────────────────
-- Grants free ('comp') access without going through Stripe at all.
-- Redemption (lookup + use-count increment + inserting the resulting
-- subscriptions row) always goes through the service-role admin client in
-- app/api/redeem-code/route.js — no user-facing policies, this table isn't
-- user-scoped so the usual "own row" RLS pattern doesn't apply.
CREATE TABLE IF NOT EXISTS public.redeem_codes (
  code        TEXT PRIMARY KEY,
  plan        TEXT NOT NULL DEFAULT 'comp',
  max_uses    INTEGER, -- NULL = unlimited
  uses_count  INTEGER NOT NULL DEFAULT 0,
  expires_at  TIMESTAMPTZ,
  -- Bonus credits granted alongside (or instead of) plan access — see the
  -- credit system section below. NULL = no credits attached to this code.
  credits     INTEGER,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.redeem_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can do anything on redeem_codes"
  ON public.redeem_codes FOR ALL
  USING (auth.role() = 'service_role');

-- ── REPORTS ──────────────────────────────────────────────────
-- One row per report generated by a LOGGED-IN visitor. This table alone is
-- the "score over time" data source (SELECT brand, score, created_at ORDER
-- BY created_at) — no separate snapshots table: every report generation IS
-- a snapshot, so a second table would just duplicate this one 1:1.
CREATE TABLE IF NOT EXISTS public.reports (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  brand       TEXT NOT NULL,
  url         TEXT,
  score       INTEGER,
  total       INTEGER NOT NULL DEFAULT 0,
  hits        INTEGER NOT NULL DEFAULT 0,
  competitors TEXT[] NOT NULL DEFAULT '{}',
  rows        JSONB, -- aiVisibility.rows: [{ query, model, live, answer, mentioned }]
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reports_user_id_created_at_idx ON public.reports(user_id, created_at DESC);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own reports"
  ON public.reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on reports"
  ON public.reports FOR ALL
  USING (auth.role() = 'service_role');

-- ── PROMPTS ──────────────────────────────────────────────────
-- User-authored AI-visibility test questions, checked on demand (see
-- app/api/prompts/[id]/check/route.js) against the same Gemini/Claude
-- models lib/aivisibility.js already uses. Latest result is denormalized
-- onto the row (last_*) rather than a separate history table — same
-- reasoning as the comment on `opportunities` above: nothing here asks for
-- a trend view, just current status per prompt.
CREATE TABLE IF NOT EXISTS public.prompts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  text             TEXT NOT NULL,
  -- 'commercial' | 'competitor' | 'branded' — user-selected when adding
  -- the prompt, not auto-classified.
  type             TEXT NOT NULL DEFAULT 'commercial',
  -- Free-text organizational label only — this app doesn't pass any
  -- region parameter to Gemini/Claude, so this never changes what's
  -- actually checked. Shown as a plain label, not implied to be real
  -- geo-targeting.
  location         TEXT NOT NULL DEFAULT 'Global',
  active           BOOLEAN NOT NULL DEFAULT TRUE,
  last_checked_at  TIMESTAMPTZ,
  last_mentioned   BOOLEAN,
  last_position    INTEGER,
  last_brands      TEXT[],
  last_answer      TEXT,
  last_model       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS prompts_user_id_idx ON public.prompts(user_id, created_at DESC);

ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own prompts"
  ON public.prompts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own prompts"
  ON public.prompts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own prompts"
  ON public.prompts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own prompts"
  ON public.prompts FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on prompts"
  ON public.prompts FOR ALL
  USING (auth.role() = 'service_role');

-- ── PROMPT CHECKS ────────────────────────────────────────────
-- Immutable history log — one row per "Check now" run (see
-- app/api/prompts/[id]/check/route.js), alongside prompts.last_* which
-- stays as the current-state cache. Same split as credit_balances
-- (cache) + credit_transactions (immutable ledger). No user-facing
-- INSERT policy — written only by the check route's service-role client.
CREATE TABLE IF NOT EXISTS public.prompt_checks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  prompt_id   UUID NOT NULL REFERENCES public.prompts(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  mentioned   BOOLEAN,
  position    INTEGER,
  brands      TEXT[],
  answer      TEXT,
  model       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS prompt_checks_prompt_id_idx ON public.prompt_checks(prompt_id, created_at DESC);

ALTER TABLE public.prompt_checks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own prompt checks"
  ON public.prompt_checks FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on prompt_checks"
  ON public.prompt_checks FOR ALL
  USING (auth.role() = 'service_role');

-- ── REPORT DRAFTS ────────────────────────────────────────────
-- Persisted version of the AI-drafted Reddit post suggestion + posted
-- status. Anonymous visitors never write here — PostDraftActions.js keeps
-- its current local-state-only behavior when there's no draftId. Nothing
-- in this table is ever posted to Reddit automatically; `posted` just
-- records that the customer says they posted it themselves.
CREATE TABLE IF NOT EXISTS public.report_drafts (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  report_id  UUID REFERENCES public.reports(id) ON DELETE CASCADE,
  -- 'comment' | 'post' | 'reply' — which Draft Studio type this came from.
  -- NULL on rows saved before this column existed.
  type       TEXT,
  subreddit  TEXT NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  posted     BOOLEAN NOT NULL DEFAULT FALSE,
  posted_at  TIMESTAMPTZ,
  -- Self-reported link to the live post, once the customer has actually
  -- posted it themselves — lets Track Tasks show a "view live" link. We
  -- don't auto-fetch upvotes/removal status here (Reddit blocks direct
  -- fetches from cloud IPs, same constraint documented in lib/reddit.js),
  -- so this stays a self-reported reference, not a scraped metric.
  permalink  TEXT,
  -- Poster (public.users.role = 'poster') who currently holds this task —
  -- see app/poster/**. NULL = sitting in the open marketplace pool,
  -- unclaimed. Still admin-settable directly for a manual override/VIP
  -- routing (components/AssignDraftControl.js), but the primary path is
  -- now self-claim (see app/api/poster/tasks/[id]/claim).
  claimed_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  -- 'available' (open in the marketplace) | 'claimed' (locked to
  -- claimed_by until claim_expires_at) | 'submitted' (permalink pasted —
  -- cosmetically "Approved" too, there's no review gate) | 'paid' (an
  -- admin has recorded a poster_payouts row covering this task's period;
  -- see lib/posterTasks.js for how "paid" gets applied).
  status     TEXT NOT NULL DEFAULT 'available',
  claimed_at TIMESTAMPTZ,
  -- Lazily enforced (no cron in this app) — a claim past this time is
  -- treated as expired/released the next time anything reads or claims
  -- it, rather than needing a background sweep.
  claim_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS report_drafts_user_id_idx ON public.report_drafts(user_id);
CREATE INDEX IF NOT EXISTS report_drafts_claimed_by_idx ON public.report_drafts(claimed_by);
CREATE INDEX IF NOT EXISTS report_drafts_status_idx ON public.report_drafts(status);

ALTER TABLE public.report_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own drafts"
  ON public.report_drafts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own drafts"
  ON public.report_drafts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own drafts"
  ON public.report_drafts FOR UPDATE
  USING (auth.uid() = user_id);

-- A poster's own uid matching claimed_by is sufficient proof of
-- ownership — only the service-role client (admin) ever sets claimed_by
-- on a row that wasn't already theirs (the atomic claim operation), so
-- this can't be self-granted for someone else's task.
CREATE POLICY "Posters can read claimed drafts"
  ON public.report_drafts FOR SELECT
  USING (auth.uid() = claimed_by);

CREATE POLICY "Posters can update claimed drafts"
  ON public.report_drafts FOR UPDATE
  USING (auth.uid() = claimed_by);

-- No "posters can read available drafts" policy — the marketplace list
-- (unclaimed rows across ALL customers) is deliberately read only via the
-- service-role client, scoped in application code
-- (app/api/poster/tasks/route.js), not opened up via RLS. A broad
-- status='available' policy would let any authenticated customer session
-- read OTHER customers' unclaimed draft titles/subreddits too, since RLS
-- policies are OR'd together — not worth the exposure for a read that's
-- easy to do safely server-side instead.

CREATE POLICY "Service role can do anything on report_drafts"
  ON public.report_drafts FOR ALL
  USING (auth.role() = 'service_role');

-- ── OPPORTUNITIES ────────────────────────────────────────────
-- Cached Reddit threads matched + relevance-scored against a user's
-- company profile. Refreshed on demand (via the dashboard's Refresh
-- button, not on every page load) — a refresh deletes the user's old rows
-- and inserts the new batch, it's a replace, not an append.
CREATE TABLE IF NOT EXISTS public.opportunities (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  sub              TEXT NOT NULL,
  title            TEXT NOT NULL,
  snippet          TEXT,
  permalink        TEXT NOT NULL,
  ups              INTEGER NOT NULL DEFAULT 0,
  comments         INTEGER NOT NULL DEFAULT 0,
  post_created_at  TIMESTAMPTZ,
  relevance_score  INTEGER,
  relevance_reason TEXT,
  -- 2-4 short checkmark-style bullets from the same batched scoring call —
  -- backs the "Why AEOrank recommends this" list. relevance_reason (above)
  -- stays as the single-sentence version other UI (dashboard spotlight)
  -- already reads.
  relevance_reasons TEXT[],
  -- Judgment call from the same batched scoring call as relevance_score —
  -- "high"/"medium"/"low", not a fact lookup, so it belongs alongside the
  -- score rather than needing its own LLM call.
  buying_intent    TEXT,
  -- Pins a row so a refresh's delete-and-replace cache logic (below) skips
  -- it — the only way anything here survives a refresh.
  saved            BOOLEAN NOT NULL DEFAULT FALSE,
  -- On-demand deep analysis (see app/api/opportunities/analyze/route.js) —
  -- unlike relevance_score/buying_intent, these come from the thread's
  -- actual fetched body + comments, not just the title/snippet, so they're
  -- only populated when a user explicitly asks for them (separately
  -- credit-metered) rather than for every row on every refresh.
  analysis_summary               TEXT,
  analysis_pain_points           TEXT[],
  analysis_competitors_mentioned TEXT[],
  analysis_response_angle        TEXT,
  analyzed_at                    TIMESTAMPTZ,
  fetched_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS opportunities_user_id_idx ON public.opportunities(user_id, relevance_score DESC);

ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own opportunities"
  ON public.opportunities FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own opportunities"
  ON public.opportunities FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Lets a user toggle their own `saved` flag directly (mirrors "Users can
-- update own drafts" on report_drafts) — the analysis_* columns are never
-- written this way, only via the service-role client in the analyze route.
CREATE POLICY "Users can update own opportunities"
  ON public.opportunities FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own opportunities"
  ON public.opportunities FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on opportunities"
  ON public.opportunities FOR ALL
  USING (auth.role() = 'service_role');

-- ── MENTIONS ─────────────────────────────────────────────────
-- Read-only brand-mention monitoring: real Reddit posts/comments that
-- already mention the user's brand, with AI sentiment classification.
-- Same cache-then-refresh-on-demand pattern as opportunities. Nothing
-- here posts, votes, or otherwise touches Reddit — it only searches and
-- reads what's already public.
CREATE TABLE IF NOT EXISTS public.mentions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  sub              TEXT NOT NULL,
  title            TEXT NOT NULL,
  snippet          TEXT,
  permalink        TEXT NOT NULL,
  ups              INTEGER NOT NULL DEFAULT 0,
  comments         INTEGER NOT NULL DEFAULT 0,
  post_created_at  TIMESTAMPTZ,
  sentiment        TEXT, -- positive / neutral / negative
  sentiment_reason TEXT,
  fetched_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS mentions_user_id_idx ON public.mentions(user_id, post_created_at DESC);

ALTER TABLE public.mentions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own mentions"
  ON public.mentions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own mentions"
  ON public.mentions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own mentions"
  ON public.mentions FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on mentions"
  ON public.mentions FOR ALL
  USING (auth.role() = 'service_role');

-- ── COMPANY PROFILES ─────────────────────────────────────────
-- One row per user, filled in by the post-signup onboarding wizard
-- (website, company details, competitors). Reference data only for now —
-- not yet wired into report generation. `completed` is set whether the
-- user finishes the wizard or hits "Skip onboarding", so we don't
-- re-prompt either way.
CREATE TABLE IF NOT EXISTS public.company_profiles (
  user_id           UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  website           TEXT,
  company_name      TEXT,
  target_location   TEXT,
  brand_variations  TEXT[] NOT NULL DEFAULT '{}',
  description       TEXT,
  competitors       TEXT[] NOT NULL DEFAULT '{}',
  completed         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.company_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own company profile"
  ON public.company_profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own company profile"
  ON public.company_profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own company profile"
  ON public.company_profiles FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on company_profiles"
  ON public.company_profiles FOR ALL
  USING (auth.role() = 'service_role');

-- ── CREDIT BALANCES ──────────────────────────────────────────
-- One row per user. Every mutation goes through the deduct_credits/
-- grant_credits functions below (never a direct UPDATE), so there is no
-- user-facing INSERT/UPDATE policy here — reads only.
CREATE TABLE IF NOT EXISTS public.credit_balances (
  user_id             UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  balance             INTEGER NOT NULL DEFAULT 0,
  monthly_allowance   INTEGER NOT NULL DEFAULT 0,
  allowance_reset_at  TIMESTAMPTZ,
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.credit_balances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own balance"
  ON public.credit_balances FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on credit_balances"
  ON public.credit_balances FOR ALL
  USING (auth.role() = 'service_role');

-- ── CREDIT TRANSACTIONS ──────────────────────────────────────
-- Single immutable ledger — a negative amount is a usage record, a
-- positive amount is a grant/purchase/refund/renewal. Balance is always
-- reconcilable by summing this table, so there's no separate "usage"
-- table duplicating it. No user-facing write policy; all writes happen
-- via the service-role client in lib/credits.js.
CREATE TABLE IF NOT EXISTS public.credit_transactions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount      INTEGER NOT NULL,
  action      TEXT NOT NULL,
  description TEXT,
  metadata    JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS credit_transactions_user_id_idx ON public.credit_transactions(user_id, created_at DESC);

ALTER TABLE public.credit_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own transactions"
  ON public.credit_transactions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can do anything on credit_transactions"
  ON public.credit_transactions FOR ALL
  USING (auth.role() = 'service_role');

-- ── CREDIT PACKAGES ──────────────────────────────────────────
-- Admin-managed one-time purchase options. Publicly readable (active
-- ones only) — same visibility as the PLANS pricing already shown to
-- anonymous visitors, just DB-driven instead of code-driven so admin can
-- add packages without a deploy.
CREATE TABLE IF NOT EXISTS public.credit_packages (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name           TEXT NOT NULL,
  credits        INTEGER NOT NULL,
  price_cents    INTEGER NOT NULL,
  currency       TEXT NOT NULL DEFAULT 'usd',
  active         BOOLEAN NOT NULL DEFAULT TRUE,
  -- Extra credits on top of `credits` — total granted on purchase is
  -- credits + bonus_credits (see app/api/checkout/route.js).
  bonus_credits  INTEGER NOT NULL DEFAULT 0,
  -- Admin-set marketing pill, e.g. "Most Popular" / "Best Value". NULL = none.
  badge          TEXT,
  description    TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.credit_packages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Packages are publicly readable"
  ON public.credit_packages FOR SELECT
  USING (active = true);

CREATE POLICY "Service role can do anything on credit_packages"
  ON public.credit_packages FOR ALL
  USING (auth.role() = 'service_role');

-- ── ATOMIC CREDIT FUNCTIONS ───────────────────────────────────
-- SECURITY DEFINER + explicitly REVOKEd from anon/authenticated: these
-- must only ever be called via the service-role admin client from server
-- code (lib/credits.js). A client-callable grant_credits would let anyone
-- mint their own credits. The atomic UPDATE...RETURNING avoids the
-- classic read-balance-then-write-separately race condition under
-- concurrent requests.
CREATE OR REPLACE FUNCTION public.deduct_credits(p_user_id UUID, p_amount INTEGER)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE public.credit_balances
  SET balance = balance - p_amount, updated_at = NOW()
  WHERE user_id = p_user_id AND balance >= p_amount
  RETURNING balance INTO v_new_balance;
  RETURN v_new_balance; -- NULL = insufficient balance (or no balance row yet)
END;
$$;

CREATE OR REPLACE FUNCTION public.grant_credits(p_user_id UUID, p_amount INTEGER)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_new_balance INTEGER;
BEGIN
  INSERT INTO public.credit_balances (user_id, balance)
  VALUES (p_user_id, p_amount)
  ON CONFLICT (user_id) DO UPDATE
    SET balance = public.credit_balances.balance + p_amount, updated_at = NOW()
  RETURNING balance INTO v_new_balance;
  RETURN v_new_balance;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.deduct_credits(UUID, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.grant_credits(UUID, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.deduct_credits(UUID, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_credits(UUID, INTEGER) TO service_role;

-- ── AUTO-CREATE USER PROFILE ON SIGNUP ───────────────────────
-- Fires for every auth.users insert, whether from a real magic-link login
-- OR from admin.auth.admin.createUser() called by the Stripe webhook to
-- silently provision an account for someone who paid before ever logging in.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── USERS: referral tracking ─────────────────────────────────
-- Set only by the admin-approval flow (app/api/admin/poster-applications/
-- [id]/approve/route.js) from poster_applications.referred_by at
-- account-creation time — never self-reported after the fact.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES public.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS users_referred_by_idx ON public.users(referred_by);

-- ── POSTER APPLICATIONS ──────────────────────────────────────
-- Pending signups from the public "Refer a friend" apply form
-- (app/apply-poster). No self-signup exists for posters — an application
-- here never creates an account by itself; an admin must approve it via
-- app/admin/posters, which is what actually calls auth.admin.createUser.
CREATE TABLE IF NOT EXISTS public.poster_applications (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email        TEXT NOT NULL,
  -- Resolved from the ?ref=<user-id> query param on the public apply form.
  -- NULL if there was no ref param, or it didn't match a real poster —
  -- the applicant is never blocked for a bad/missing ref.
  referred_by  UUID REFERENCES public.users(id) ON DELETE SET NULL,
  -- Normalized username (see lib/reddit.js's normalizeRedditUsername) from
  -- whatever profile link/username the applicant entered.
  reddit_username     TEXT,
  -- 'active' (via Reddit OAuth/direct fetch/Apify user-scraper) |
  -- 'active_approx' (via Pullpush's historical archive instead — an
  -- approximation, not the account itself) | 'suspended' | 'unavailable'
  -- (Apify's actor found no profile at all — likely suspended/deleted,
  -- can't tell which) | 'not_found' | 'too_new' (younger than
  -- lib/reddit.js's MIN_ACCOUNT_AGE_MONTHS) | 'low_karma' (under
  -- MIN_KARMA) | 'unverified' (couldn't check any way) | 'invalid'
  -- (unparseable input). Everything except 'active'/'active_approx'/
  -- 'unverified' is rejected at submission time in
  -- app/api/poster-applications — this column only ever holds those
  -- three for rows that made it past that.
  reddit_check_status TEXT,
  -- 'pending' (default) | 'approved' | 'dismissed'
  status       TEXT NOT NULL DEFAULT 'pending',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS poster_applications_status_idx ON public.poster_applications(status, created_at DESC);
CREATE INDEX IF NOT EXISTS poster_applications_referred_by_idx ON public.poster_applications(referred_by);

-- Only one *pending* application per email at a time — resubmission after
-- a dismissal is fine, but prevents duplicate pending rows piling up from
-- someone re-submitting the form.
CREATE UNIQUE INDEX IF NOT EXISTS poster_applications_email_pending_uidx
  ON public.poster_applications(email) WHERE status = 'pending';

ALTER TABLE public.poster_applications ENABLE ROW LEVEL SECURITY;

-- No public/user policies at all — every access (public submission via the
-- apply form, admin review/approve/dismiss) goes through createAdminClient()
-- (service role), same as redeem_codes.
CREATE POLICY "Service role can do anything on poster_applications"
  ON public.poster_applications FOR ALL
  USING (auth.role() = 'service_role');

-- ── POSTER PAYOUTS ────────────────────────────────────────────
-- Real payout ledger — each row is one payment event an admin recorded
-- (app/api/admin/posters/[id]/payouts), not a computed running total. A
-- poster's "Total paid" = sum of their own rows here; "Pending" = their
-- lifetime task earnings (computed from report_drafts, see
-- lib/posterTasks.js) minus that sum. Mirrors the credit system's
-- cache+ledger split (lib/credits.js) — the ledger is the source of
-- truth, nothing here is ever recomputed/overwritten.
CREATE TABLE IF NOT EXISTS public.poster_payouts (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  poster_id  UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount     NUMERIC(10,2) NOT NULL,
  note       TEXT,
  -- 'paid' (admin recorded an actual payment — app/api/admin/posters/[id]/
  -- payouts) | 'requested' (poster asked to withdraw via
  -- app/api/poster/withdraw, awaiting admin action — see
  -- app/api/admin/payouts/[id] for marking it paid). Only 'paid' rows
  -- count toward totalPaid in lib/posterPay.js's getEarningsSummary.
  status     TEXT NOT NULL DEFAULT 'paid',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS poster_payouts_poster_id_idx ON public.poster_payouts(poster_id, created_at DESC);

ALTER TABLE public.poster_payouts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Posters can read own payouts"
  ON public.poster_payouts FOR SELECT
  USING (auth.uid() = poster_id);

CREATE POLICY "Service role can do anything on poster_payouts"
  ON public.poster_payouts FOR ALL
  USING (auth.role() = 'service_role');
