import { createAdminClient } from "@/lib/supabase/admin";
import AssignDraftControl from "@/components/AssignDraftControl";
import AdminReviewControl from "@/components/AdminReviewControl";
import AdminDeleteDraftControl from "@/components/AdminDeleteDraftControl";
import { displaySubreddit } from "@/lib/format";

const VERIFICATION_LABEL = {
  verified: { label: "Verified", color: "var(--state-success-fg)" },
  needs_review: { label: "Needs review", color: "var(--accent)" },
  rejected: { label: "Rejected", color: "var(--state-danger-fg)" },
};

export const dynamic = "force-dynamic";

const TYPE_LABELS = { comment: "Comment", post: "Post", reply: "Reply", upvote: "Upvote" };

export default async function AdminDraftsPage() {
  const admin = createAdminClient();

  if (!admin) {
    return (
      <section className="section">
        <div className="container">
          <span className="section-tag">( admin )</span>
          <h2>Posts</h2>
          <div className="card" style={{ textAlign: "center", color: "var(--text-dim)" }}>
            Supabase service role key isn't configured.
          </div>
        </div>
      </section>
    );
  }

  const [{ data: drafts }, { data: users }, { data: posters }] = await Promise.all([
    admin
      .from("report_drafts")
      .select("id, user_id, type, subreddit, title, body, posted, posted_at, permalink, claimed_by, created_at, verification_status, status")
      .order("created_at", { ascending: false }),
    admin.from("users").select("id, email"),
    admin.from("users").select("id, email").eq("role", "poster"),
  ]);

  const emailByUser = new Map((users || []).map((u) => [u.id, u.email]));

  return (
    <section className="section">
      <div className="container">
        <span className="section-tag">( admin )</span>
        <h2>Posts</h2>
        <p className="section-sub">Every comment/post/reply generated by any customer, newest first.</p>

        {!drafts || drafts.length === 0 ? (
          <div className="card" style={{ textAlign: "center", color: "var(--text-dim)" }}>
            No posts yet.
          </div>
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", tableLayout: "fixed", minWidth: 1230 }}>
              <colgroup>
                <col style={{ width: 140 }} />
                <col style={{ width: 190 }} />
                <col style={{ width: 85 }} />
                <col style={{ width: 120 }} />
                <col />
                <col style={{ width: 90 }} />
                <col style={{ width: 110 }} />
                <col style={{ width: 190 }} />
                <col style={{ width: 80 }} />
              </colgroup>
              <thead>
                <tr style={{ borderBottom: "1px solid var(--border, rgba(255,255,255,.1))" }}>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Date</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>User</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Type</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Subreddit</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Content</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Status</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Verification</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Assigned to</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}></th>
                </tr>
              </thead>
              <tbody>
                {drafts.map((d) => (
                  <tr key={d.id} style={{ borderBottom: "1px solid var(--border, rgba(255,255,255,.06))" }}>
                    <td style={{ padding: "10px 12px", color: "var(--text-dim)", fontSize: 13, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                      {new Date(d.created_at).toLocaleString()}
                    </td>
                    <td style={{ padding: "10px 12px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                      {emailByUser.get(d.user_id) || "-"}
                    </td>
                    <td style={{ padding: "10px 12px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                      {TYPE_LABELS[d.type] || "-"}
                    </td>
                    <td style={{ padding: "10px 12px", color: "var(--text-dim)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                      r/{displaySubreddit(d.subreddit)}
                    </td>
                    <td style={{ padding: "10px 12px" }}>
                      <details>
                        <summary
                          style={{
                            cursor: "pointer",
                            fontWeight: 600,
                            whiteSpace: "nowrap",
                            overflow: "hidden",
                            textOverflow: "ellipsis",
                          }}
                        >
                          {d.title && d.title !== d.subreddit ? d.title : d.body.slice(0, 80)}
                        </summary>
                        <div style={{ color: "var(--text-dim)", fontSize: 13, lineHeight: 1.5, marginTop: 6, whiteSpace: "pre-wrap" }}>
                          {d.body}
                        </div>
                      </details>
                    </td>
                    <td style={{ padding: "10px 12px", whiteSpace: "nowrap" }}>
                      {d.posted ? (
                        <span style={{ color: "var(--msg-success)" }}>
                          Posted
                          {d.permalink && (
                            <>
                              {" · "}
                              <a href={d.permalink} target="_blank" rel="noopener noreferrer">
                                view
                              </a>
                            </>
                          )}
                        </span>
                      ) : (
                        <span style={{ color: "var(--text-dim)" }}>Pending</span>
                      )}
                    </td>
                    <td style={{ padding: "10px 12px" }}>
                      {d.verification_status ? (
                        <div style={{ display: "flex", flexDirection: "column", gap: 6, alignItems: "flex-start" }}>
                          <span style={{ color: VERIFICATION_LABEL[d.verification_status]?.color, fontWeight: 600, fontSize: 13 }}>
                            {VERIFICATION_LABEL[d.verification_status]?.label || d.verification_status}
                          </span>
                          {d.verification_status === "needs_review" && <AdminReviewControl draftId={d.id} />}
                        </div>
                      ) : (
                        <span style={{ color: "var(--text-muted)", fontSize: 13 }}>-</span>
                      )}
                    </td>
                    <td style={{ padding: "10px 12px" }}>
                      <AssignDraftControl draftId={d.id} posters={posters || []} initialClaimedBy={d.claimed_by} />
                    </td>
                    <td style={{ padding: "10px 12px" }}>
                      {d.status !== "submitted" && <AdminDeleteDraftControl draftId={d.id} />}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}
