import { createAdminClient } from "@/lib/supabase/admin";
import AssignDraftControl from "@/components/AssignDraftControl";
import { displaySubreddit } from "@/lib/format";

export const dynamic = "force-dynamic";

const TYPE_LABELS = { comment: "Comment", post: "Post", reply: "Reply", upvote: "Upvote" };

export default async function AdminDraftsPage() {
  const admin = createAdminClient();

  if (!admin) {
    return (
      <section className="section">
        <div className="container">
          <span className="section-tag">( admin )</span>
          <h2>Posts</h2>
          <div className="card" style={{ textAlign: "center", color: "var(--text-dim)" }}>
            Supabase service role key isn't configured.
          </div>
        </div>
      </section>
    );
  }

  const [{ data: drafts }, { data: users }, { data: posters }] = await Promise.all([
    admin
      .from("report_drafts")
      .select("id, user_id, type, subreddit, title, body, posted, posted_at, permalink, claimed_by, created_at")
      .order("created_at", { ascending: false }),
    admin.from("users").select("id, email"),
    admin.from("users").select("id, email").eq("role", "poster"),
  ]);

  const emailByUser = new Map((users || []).map((u) => [u.id, u.email]));

  return (
    <section className="section">
      <div className="container">
        <span className="section-tag">( admin )</span>
        <h2>Drafts</h2>
        <p className="section-sub">Every comment/post/reply generated by any customer, newest first.</p>

        {!drafts || drafts.length === 0 ? (
          <div className="card" style={{ textAlign: "center", color: "var(--text-dim)" }}>
            No posts yet.
          </div>
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ borderBottom: "1px solid var(--border, rgba(255,255,255,.1))" }}>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Date</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>User</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Type</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Subreddit</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Content</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Status</th>
                  <th style={{ textAlign: "left", padding: "10px 12px", color: "var(--text-dim)", fontSize: 13 }}>Assigned to</th>
                </tr>
              </thead>
              <tbody>
                {drafts.map((d) => (
                  <tr key={d.id} style={{ borderBottom: "1px solid var(--border, rgba(255,255,255,.06))" }}>
                    <td style={{ padding: "10px 12px", color: "var(--text-dim)", whiteSpace: "nowrap" }}>
                      {new Date(d.created_at).toLocaleString()}
                    </td>
                    <td style={{ padding: "10px 12px" }}>{emailByUser.get(d.user_id) || "—"}</td>
                    <td style={{ padding: "10px 12px" }}>{TYPE_LABELS[d.type] || "—"}</td>
                    <td style={{ padding: "10px 12px", color: "var(--text-dim)" }}>r/{displaySubreddit(d.subreddit)}</td>
                    <td style={{ padding: "10px 12px", maxWidth: 420 }}>
                      {d.title && d.title !== d.subreddit && (
                        <div style={{ fontWeight: 600, marginBottom: 3 }}>{d.title}</div>
                      )}
                      <div style={{ color: "var(--text-dim)", fontSize: 13, lineHeight: 1.5 }}>
                        {d.body.length > 160 ? `${d.body.slice(0, 160)}…` : d.body}
                      </div>
                    </td>
                    <td style={{ padding: "10px 12px", whiteSpace: "nowrap" }}>
                      {d.posted ? (
                        <span style={{ color: "#7ee3a3" }}>
                          Posted
                          {d.permalink && (
                            <>
                              {" · "}
                              <a href={d.permalink} target="_blank" rel="noopener noreferrer">
                                view
                              </a>
                            </>
                          )}
                        </span>
                      ) : (
                        <span style={{ color: "var(--text-dim)" }}>Draft</span>
                      )}
                    </td>
                    <td style={{ padding: "10px 12px" }}>
                      <AssignDraftControl draftId={d.id} posters={posters || []} initialClaimedBy={d.claimed_by} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </section>
  );
}
